language:
  php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

cache:
  directories:
    - vendor

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-lowest
